test_pass: fhiclpy.py
	python fhiclpy.py < testFiles/pass/assoc_pass.fcl
	python fhiclpy.py < testFiles/pass/hname_pass.fcl
	python fhiclpy.py < testFiles/pass/comments_pass.fcl
	python fhiclpy.py < testFiles/pass/include_pass.fcl
	python fhiclpy.py < testFiles/pass/leading_zero_pass.fcl
	python fhiclpy.py < testFiles/pass/names_pass.fcl
	python fhiclpy.py < testFiles/pass/prolog_pass.fcl
	python fhiclpy.py < testFiles/pass/recursion_pass.fcl
	python fhiclpy.py < testFiles/pass/ref_pass.fcl
	python fhiclpy.py < testFiles/pass/seq_pass.fcl
	python fhiclpy.py < testFiles/pass/string_pass.fcl
	python fhiclpy.py < testFiles/pass/table_pass.fcl
	python fhiclpy.py < testFiles/pass/hname_pro_pass.fcl
	python fhiclpy.py < testFiles/pass/hname2_pass.fcl      
	python fhiclpy.py < testFiles/pass/override_pass.fcl
	python fhiclpy.py < testFiles/pass/override2_pass.fcl
	python fhiclpy.py < testFiles/pass/combo_exist_pass.fcl
	python fhiclpy.py < testFiles/pass/combo_new_pass.fcl
	python fhiclpy.py < testFiles/pass/adv_num_pass.fcl
	python fhiclpy.py < testFiles/pass/adv_string_pass.fcl
	python fhiclpy.py < testFiles/pass/adv_ref_pass.fcl
	python fhiclpy.py < testFiles/pass/adv_ref2_pass.fcl
	python fhiclpy.py < testFiles/pass/adv_ref3_pass.fcl
	python fhiclpy.py < testFiles/pass/adv_ref4_pass.fcl
	python fhiclpy.py < testFiles/pass/adv_ref5_pass.fcl
	python fhiclpy.py < testFiles/pass/adv_test_pass.fcl

test_fail: fhiclpy.py
	python fhiclpy.py < testFiles/fail/assoc_fail.fcl
	python fhiclpy.py < testFiles/fail/assoc2_fail.fcl
	python fhiclpy.py < testFiles/fail/hname_fail.fcl
	python fhiclpy.py < testFiles/fail/include_fail.fcl
	python fhiclpy.py < testFiles/fail/include2_fail.fcl
	python fhiclpy.py < testFiles/fail/include3_fail.fcl
	python fhiclpy.py < testFiles/fail/leading_zero_fail.fcl
	python fhiclpy.py < testFiles/fail/name_fail.fcl
	python fhiclpy.py < testFiles/fail/prolog2_fail.fcl
	python fhiclpy.py < testFiles/fail/prolog_fail.fcl
	python fhiclpy.py < testFiles/fail/ref_fail.fcl
	python fhiclpy.py < testFiles/fail/seq_fail.fcl
	python fhiclpy.py < testFiles/fail/table_fail.fcl
	python fhiclpy.py < testFiles/fail/adv_string_fail.fcl
	python fhiclpy.py < testFiles/fail/adv_ref_fail.fcl
